module net.jchad {
    requires javafx.controls;
    requires javafx.fxml;
    requires com.google.gson;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires com.fasterxml.jackson.dataformat.yaml;
    requires com.fasterxml.jackson.databind;
    requires java.desktop;
    requires org.junit.jupiter.api;
    requires org.junit.jupiter.engine;
    requires org.junit.jupiter.params;
    requires org.junit.platform.engine;
    requires org.junit.platform.commons;
    requires org.jline;
    requires org.fxmisc.richtext;
    requires jdk.unsupported;
    requires javafx.web;
    requires org.controlsfx.controls;

    exports net.jchad.client.view;
    opens net.jchad.server.view.dashboard;
    opens net.jchad.client to javafx.fxml;
    opens net.jchad.shared.networking.packets to com.google.gson;
    opens net.jchad.shared.networking.ip to com.google.gson;
    opens net.jchad.server.model.config to com.fasterxml.jackson.databind;
    exports net.jchad.server.model.chats to com.fasterxml.jackson.databind;
    exports net.jchad.installer.gui;
    exports net.jchad.installer.serializable to com.google.gson;
    opens net.jchad.client.model.client to javafx.fxml;
    opens net.jchad.shared.common to com.fasterxml.jackson.databind;
    exports net.jchad.server.view to javafx.graphics;
    opens net.jchad.server.model.config.store to com.fasterxml.jackson.databind;
    opens net.jchad.server.model.chats to com.google.gson;
    exports net.jchad.tests.shared;
    opens net.jchad.shared.networking.packets.password to com.google.gson;
    opens net.jchad.shared.networking.packets.username to com.google.gson;
    opens net.jchad.shared.networking.packets.encryption to com.google.gson;
    opens net.jchad.shared.networking.packets.messages to com.google.gson;
    opens net.jchad.shared.networking.packets.defaults to com.google.gson;
    opens net.jchad.client.model.client.config to com.google.gson;
    opens net.jchad.client.model.store.connection to com.google.gson;
    opens net.jchad.client.model.client.testing to javafx.fxml;
    exports net.jchad.client.view.gui;
}